apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-finance
  labels:
    app: javawebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javawbapp
  template:
    metadata:
      name: jawawebappdeploy
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: ravighaddam/ravi-bankapp
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp-np-service
  labels:
    app: javawebapp
spec:
  selector:
    app: javawebapp

  type: NodePort
  ports:
  - nodePort: 31002   
    port: 80
    targetPort: 8081
